### ISSUE TITLE
Non-admins can't export 

### ISSUE THREAD

**Issue by calvin-fisher** [envkey/envkey-app#54]
As an admin, I can export all values:
![image](https://user-images.githubusercontent.com/1797159/91483228-f9022200-e86c-11ea-83e5-55ae610814ee.png)

Non-admin users do not have this button, even though they can still see all of the keys for a given environment:
![image](https://user-images.githubusercontent.com/1797159/91483275-146d2d00-e86d-11ea-80c5-bdc512cf7c53.png)

**Comment by danenania** [comment]
This is working as intended for now--the intention is to discourage making additional copies of secrets unless absolutely necessary, since having extra copies floating around is a liability for security. That said, adding flexibility here is on the roadmap.

As a workaround, non-admins can accomplish the same thing using [envkey-fetch](https://github.com/envkey/envkey-fetch) (for json) or [envkey-source](https://github.com/envkey/envkey-source) for key-value pairs.
